import { NonRetriableError } from "inngest";

import { PARSER_MODEL, PROMPT_VERSION, SCORER_MODEL } from "@/lib/llm/anthropic";
import { parseResume } from "@/lib/llm/parse-resume";
import type { ParsedResume, Scoring } from "@/lib/llm/schemas";
import { scoreResume } from "@/lib/llm/score-resume";
import { createServiceClient } from "@/lib/supabase/service";

import {
  CandidateResumeParsedEvent,
  inngest,
  ResumeUploadedEvent,
} from "../client";

// The DB types are regenerated by `npm run supabase:types` after running the
// 20260516130000_resume_llm_metadata.sql migration. Until then, the new columns
// (file_hash, is_current, seniority_level, total_years_exp, parser_model,
// scorer_model, prompt_version) aren't on the generated types — cast to keep
// TS happy. Remove the casts after regen.
type ResumesUpdate = Record<string, unknown>;

type ResumeRowExtended = {
  id: string;
  profile_id: string;
  raw_file_url: string;
  file_hash: string | null;
};

type DuplicateRow = {
  parsed_json: (ParsedResume & { scoring?: Scoring }) | null;
};

export const parseResumeFn = inngest.createFunction(
  {
    id: "parse-resume",
    retries: 2,
    concurrency: { limit: 10 },
    triggers: [ResumeUploadedEvent],
    onFailure: async ({ event, error }) => {
      const inner = (event.data as { event?: { data?: { resumeId?: string } } })
        .event;
      const resumeId = inner?.data?.resumeId;
      if (!resumeId) return;
      const supabase = createServiceClient();
      await supabase
        .from("resumes")
        .update({
          status: "failed",
          parse_error: error.message.slice(0, 1000),
        })
        .eq("id", resumeId);
    },
  },
  async ({ event, step }) => {
    const { resumeId } = event.data as {
      resumeId: string;
      profileId: string;
    };
    const supabase = createServiceClient();

    const resume = await step.run("fetch-row", async () => {
      const { data, error } = await supabase
        .from("resumes")
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        .select("id, profile_id, raw_file_url, file_hash" as any)
        .eq("id", resumeId)
        .maybeSingle();
      if (error) throw new Error(`fetch-row: ${error.message}`);
      if (!data) throw new NonRetriableError(`Resume ${resumeId} not found`);
      return data as unknown as ResumeRowExtended;
    });

    await step.run("mark-processing", async () => {
      const update: ResumesUpdate = {
        status: "processing",
        parse_started_at: new Date().toISOString(),
        parse_error: null,
      };
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      await supabase.from("resumes").update(update as any).eq("id", resumeId);
    });

    const duplicate = await step.run("check-dedup", async () => {
      if (!resume.file_hash) return null;
      const { data } = await supabase
        .from("resumes")
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        .select("parsed_json" as any)
        .eq("profile_id", resume.profile_id)
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        .eq("file_hash" as any, resume.file_hash)
        .eq("status", "complete")
        .neq("id", resumeId)
        .order("parsed_at", { ascending: false })
        .limit(1)
        .maybeSingle();
      return (data as unknown as DuplicateRow | null) ?? null;
    });

    let parsed: ParsedResume;
    let scoring: Scoring;

    if (duplicate?.parsed_json?.scoring) {
      parsed = duplicate.parsed_json;
      scoring = duplicate.parsed_json.scoring;
    } else {
      const pdfBase64 = await step.run("download-pdf", async () => {
        const res = await fetch(resume.raw_file_url);
        if (!res.ok) {
          throw new Error(`download-pdf: ${res.status} ${res.statusText}`);
        }
        const ab = await res.arrayBuffer();
        return Buffer.from(ab).toString("base64");
      });

      parsed = await step.run("parse-claude", async () => {
        return parseResume(Buffer.from(pdfBase64, "base64"));
      });

      scoring = await step.run("score-claude", async () => {
        return scoreResume(parsed);
      });
    }

    await step.run("write-result", async () => {
      const update: ResumesUpdate = {
        parsed_text: parsed.raw_text,
        parsed_json: { ...parsed, scoring },
        ats_score: scoring.overall,
        seniority_level: parsed.seniority_level,
        total_years_exp: parsed.total_years_exp,
        status: "complete",
        parsed_at: new Date().toISOString(),
        is_current: true,
        parser_model: PARSER_MODEL,
        scorer_model: SCORER_MODEL,
        prompt_version: PROMPT_VERSION,
        parse_error: null,
      };
      const { error } = await supabase
        .from("resumes")
        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        .update(update as any)
        .eq("id", resumeId);
      if (error) throw new Error(`write-result: ${error.message}`);
    });

    await step.sendEvent(
      "notify-downstream",
      CandidateResumeParsedEvent.create({
        resumeId,
        profileId: resume.profile_id,
        atsScore: scoring.overall,
      })
    );

    return { resumeId, atsScore: scoring.overall, deduped: !!duplicate };
  }
);
